apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 3  # Set the number of replicas to 3
  selector:
    matchLabels:
      app: springboot-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Ensures at least one pod is available during update
      maxSurge: 1        # Allows one extra pod to be started during the update
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql-headless 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: springboot-app
        image: your-dockerhub-username/springboot-app:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-headless:3306/$(DATABASE_NAME)?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-name
        ports:
        - containerPort: 8080
